// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/metaparticle-io/metaparticle-ast/models"
)

// CreateOrUpdateServiceOKCode is the HTTP code returned for type CreateOrUpdateServiceOK
const CreateOrUpdateServiceOKCode int = 200

/*CreateOrUpdateServiceOK OK

swagger:response createOrUpdateServiceOK
*/
type CreateOrUpdateServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.Service `json:"body,omitempty"`
}

// NewCreateOrUpdateServiceOK creates CreateOrUpdateServiceOK with default headers values
func NewCreateOrUpdateServiceOK() *CreateOrUpdateServiceOK {
	return &CreateOrUpdateServiceOK{}
}

// WithPayload adds the payload to the create or update service o k response
func (o *CreateOrUpdateServiceOK) WithPayload(payload *models.Service) *CreateOrUpdateServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update service o k response
func (o *CreateOrUpdateServiceOK) SetPayload(payload *models.Service) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CreateOrUpdateServiceDefault error

swagger:response createOrUpdateServiceDefault
*/
type CreateOrUpdateServiceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateOrUpdateServiceDefault creates CreateOrUpdateServiceDefault with default headers values
func NewCreateOrUpdateServiceDefault(code int) *CreateOrUpdateServiceDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateOrUpdateServiceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create or update service default response
func (o *CreateOrUpdateServiceDefault) WithStatusCode(code int) *CreateOrUpdateServiceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create or update service default response
func (o *CreateOrUpdateServiceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create or update service default response
func (o *CreateOrUpdateServiceDefault) WithPayload(payload *models.Error) *CreateOrUpdateServiceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create or update service default response
func (o *CreateOrUpdateServiceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateOrUpdateServiceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
