// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateOrUpdateServiceHandlerFunc turns a function with the right signature into a create or update service handler
type CreateOrUpdateServiceHandlerFunc func(CreateOrUpdateServiceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateOrUpdateServiceHandlerFunc) Handle(params CreateOrUpdateServiceParams) middleware.Responder {
	return fn(params)
}

// CreateOrUpdateServiceHandler interface for that can handle valid create or update service params
type CreateOrUpdateServiceHandler interface {
	Handle(CreateOrUpdateServiceParams) middleware.Responder
}

// NewCreateOrUpdateService creates a new http.Handler for the create or update service operation
func NewCreateOrUpdateService(ctx *middleware.Context, handler CreateOrUpdateServiceHandler) *CreateOrUpdateService {
	return &CreateOrUpdateService{Context: ctx, Handler: handler}
}

/*CreateOrUpdateService swagger:route PUT /services/{name} services createOrUpdateService

CreateOrUpdateService create or update service API

*/
type CreateOrUpdateService struct {
	Context *middleware.Context
	Handler CreateOrUpdateServiceHandler
}

func (o *CreateOrUpdateService) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateOrUpdateServiceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
