consumes:
- application/json
definitions:
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  build:
    type: object
    properties:
      name:
        type: string
      path:
        type: string
      imageName:
        type: string
  jobSpecification:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      containers:
        type: array
        items:
          $ref: '#/definitions/container'
      volumes:
        type: array
        items:
          $ref: '#/definitions/volume'
      parallelism:
        type: integer
        format: int32
      completion:
        type: integer
        format: int32
      schedule:
        type: string
  tfJobSpecification:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      replicaSpecs:
        type: array
        items:
          $ref: '#/definitions/tfReplicaSpec'
  shardSpecification:
    type: object
    properties:
      # JSONPath for reaching into an object.
      fieldPath:
        type: string
      # Regular Expression for matching in a URL
      urlPattern:
        type: string
      shards:
        type: integer
        format: int32
  serveSpecification:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      public:
        type: boolean
  tfReplicaSpec:
    type: object
    properties:
      replicas:
        type: integer
        format: int32
      replicaType:
        type: string
        enum:
          - MASTER
          - WORKER
          - PS
      containers:
        type: array
        items:
          $ref: '#/definitions/container'
      volumes:
        type: array
        items:
          $ref: '#/definitions/volume'
  envVar:
    type: object
    required:
    - name
    - value
    properties:
      name:
        type: string
      value:
        type: string
  volume:
    type: object
    required:
      - name
      - persistentVolumeClaim
    properties:
      name:
        type: string
      persistentVolumeClaim:
        type: string
  volumeMount:
    type: object
    required:
      - name
      - mountPath
    properties:
      name:
        type: string
      mountPath:
        type: string
      subPath:
        type: string
  container:
    type: object
    required:
    - image
    properties:
      image:
        type: string
      command:
        type: array
        items:
          type: string
      env:
        type: array
        items:
          $ref: '#/definitions/envVar'
      volumeMounts:
        type: array
        items:
          $ref: '#/definitions/volumeMount'
      gpu:
        type: integer
        format: int32
      cpu:
        type: string
      memory:
        type: string
  servicePort:
    type: object
    required:
    - number
    properties:
      number:
        type: integer
        format: int32
      protocol:
        type: string
  serviceSpecification:
    type: object
    required:
    - name
    properties:
      name:
        type: string
      replicas:
        type: integer
        format: int32
      shardSpec:
        $ref: '#/definitions/shardSpecification'
      containers:
        type: array
        items:
          $ref: '#/definitions/container'
      volumes:
        type: array
        items:
          $ref: '#/definitions/volume'
      ports:
        type: array
        items:
          $ref: '#/definitions/servicePort'
      reference:
        type: string
      depends:
        type: string
  service:
    type: object
    required:
    - guid
    - name
    properties:
      guid:
        type: integer
        format: int64
      name:
        type: string
        minLength: 1
      services:
        type: array
        items:
          $ref: '#/definitions/serviceSpecification'
      jobs:
        type: array
        items:
          $ref: '#/definitions/jobSpecification'
      tfJobs:
        type: array
        items:
          $ref: '#/definitions/tfJobSpecification'
      serve:
        type: object
        $ref: '#/definitions/serveSpecification'
info:
  description: The metaparticle API
  title: An application for easier distributed application generation
  version: 0.0.1
paths:
  /services:
    get:
      operationId: listServices
      tags:
        - services
      responses:
        200:
          description: list the services
          schema:
            type: array
            items:
              $ref: "#/definitions/service"
  /services/{name}:
    parameters:
    - type: string
      name: name
      in: path
      required: true
    get:
      tags:
      - services
      operationId: getService
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/service"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
      - services
      operationId: createOrUpdateService
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/service"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/service"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - services
      operationId: deleteService
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
produces:
- application/json
schemes:
- http
swagger: "2.0"
