// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi An application for easier distributed application generation

The metaparticle API


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json


    Produces:
    - application/json


swagger:meta
*/
package restapi
