// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "The metaparticle API",
    "title": "An application for easier distributed application generation",
    "version": "0.0.1"
  },
  "paths": {
    "/services": {
      "get": {
        "tags": [
          "services"
        ],
        "responses": {
          "200": {
            "description": "list the services",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/service"
              }
            }
          }
        }
      }
    },
    "/services/{name}": {
      "get": {
        "tags": [
          "services"
        ],
        "operationId": "getOne",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/service"
            }
          }
        }
      },
      "put": {
        "tags": [
          "services"
        ],
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/service"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/service"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "services"
        ],
        "operationId": "destroyOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "string",
          "name": "name",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "service": {
      "type": "object",
      "required": [
        "guid",
        "name"
      ],
      "properties": {
        "guid": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "services": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/serviceSpecification"
          }
        }
      }
    },
    "serviceSpecification": {
      "type": "object",
      "required": [
        "replicas"
      ],
      "properties": {
        "depends": {
          "type": "string"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "reference": {
          "type": "string"
        },
        "replicas": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  }
}`))
}
