// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/metaparticle-io/metaparticle-ast/models"
)

// NewCreateOrUpdateServiceParams creates a new CreateOrUpdateServiceParams object
// with the default values initialized.
func NewCreateOrUpdateServiceParams() *CreateOrUpdateServiceParams {
	var ()
	return &CreateOrUpdateServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateOrUpdateServiceParamsWithTimeout creates a new CreateOrUpdateServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateOrUpdateServiceParamsWithTimeout(timeout time.Duration) *CreateOrUpdateServiceParams {
	var ()
	return &CreateOrUpdateServiceParams{

		timeout: timeout,
	}
}

// NewCreateOrUpdateServiceParamsWithContext creates a new CreateOrUpdateServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateOrUpdateServiceParamsWithContext(ctx context.Context) *CreateOrUpdateServiceParams {
	var ()
	return &CreateOrUpdateServiceParams{

		Context: ctx,
	}
}

// NewCreateOrUpdateServiceParamsWithHTTPClient creates a new CreateOrUpdateServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateOrUpdateServiceParamsWithHTTPClient(client *http.Client) *CreateOrUpdateServiceParams {
	var ()
	return &CreateOrUpdateServiceParams{
		HTTPClient: client,
	}
}

/*CreateOrUpdateServiceParams contains all the parameters to send to the API endpoint
for the create or update service operation typically these are written to a http.Request
*/
type CreateOrUpdateServiceParams struct {

	/*Body*/
	Body *models.Service
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create or update service params
func (o *CreateOrUpdateServiceParams) WithTimeout(timeout time.Duration) *CreateOrUpdateServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create or update service params
func (o *CreateOrUpdateServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create or update service params
func (o *CreateOrUpdateServiceParams) WithContext(ctx context.Context) *CreateOrUpdateServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create or update service params
func (o *CreateOrUpdateServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create or update service params
func (o *CreateOrUpdateServiceParams) WithHTTPClient(client *http.Client) *CreateOrUpdateServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create or update service params
func (o *CreateOrUpdateServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create or update service params
func (o *CreateOrUpdateServiceParams) WithBody(body *models.Service) *CreateOrUpdateServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create or update service params
func (o *CreateOrUpdateServiceParams) SetBody(body *models.Service) {
	o.Body = body
}

// WithName adds the name to the create or update service params
func (o *CreateOrUpdateServiceParams) WithName(name string) *CreateOrUpdateServiceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the create or update service params
func (o *CreateOrUpdateServiceParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CreateOrUpdateServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
