// Code generated by go-swagger; DO NOT EDIT.

package services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/metaparticle-io/metaparticle-ast/models"
)

// DeleteServiceReader is a Reader for the DeleteService structure.
type DeleteServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteServiceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteServiceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteServiceNoContent creates a DeleteServiceNoContent with default headers values
func NewDeleteServiceNoContent() *DeleteServiceNoContent {
	return &DeleteServiceNoContent{}
}

/*DeleteServiceNoContent handles this case with default header values.

Deleted
*/
type DeleteServiceNoContent struct {
}

func (o *DeleteServiceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}][%d] deleteServiceNoContent ", 204)
}

func (o *DeleteServiceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteServiceDefault creates a DeleteServiceDefault with default headers values
func NewDeleteServiceDefault(code int) *DeleteServiceDefault {
	return &DeleteServiceDefault{
		_statusCode: code,
	}
}

/*DeleteServiceDefault handles this case with default header values.

error
*/
type DeleteServiceDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete service default response
func (o *DeleteServiceDefault) Code() int {
	return o._statusCode
}

func (o *DeleteServiceDefault) Error() string {
	return fmt.Sprintf("[DELETE /services/{name}][%d] deleteService default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteServiceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
