// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceSpecification service specification
// swagger:model serviceSpecification
type ServiceSpecification struct {

	// containers
	Containers ServiceSpecificationContainers `json:"containers"`

	// depends
	Depends string `json:"depends,omitempty"`

	// name
	// Required: true
	Name *string `json:"name"`

	// ports
	Ports ServiceSpecificationPorts `json:"ports"`

	// reference
	Reference string `json:"reference,omitempty"`

	// replicas
	Replicas int32 `json:"replicas,omitempty"`

	// shard spec
	ShardSpec *ShardSpecification `json:"shardSpec,omitempty"`

	// volumes
	Volumes ServiceSpecificationVolumes `json:"volumes"`
}

// Validate validates this service specification
func (m *ServiceSpecification) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateShardSpec(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceSpecification) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *ServiceSpecification) validateShardSpec(formats strfmt.Registry) error {

	if swag.IsZero(m.ShardSpec) { // not required
		return nil
	}

	if m.ShardSpec != nil {

		if err := m.ShardSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("shardSpec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceSpecification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceSpecification) UnmarshalBinary(b []byte) error {
	var res ServiceSpecification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
