// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TfReplicaSpec tf replica spec
// swagger:model tfReplicaSpec
type TfReplicaSpec struct {

	// containers
	Containers TfReplicaSpecContainers `json:"containers"`

	// replica type
	ReplicaType string `json:"replicaType,omitempty"`

	// replicas
	Replicas int32 `json:"replicas,omitempty"`

	// volumes
	Volumes TfReplicaSpecVolumes `json:"volumes"`
}

// Validate validates this tf replica spec
func (m *TfReplicaSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReplicaType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var tfReplicaSpecTypeReplicaTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MASTER","WORKER","PS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		tfReplicaSpecTypeReplicaTypePropEnum = append(tfReplicaSpecTypeReplicaTypePropEnum, v)
	}
}

const (
	// TfReplicaSpecReplicaTypeMASTER captures enum value "MASTER"
	TfReplicaSpecReplicaTypeMASTER string = "MASTER"
	// TfReplicaSpecReplicaTypeWORKER captures enum value "WORKER"
	TfReplicaSpecReplicaTypeWORKER string = "WORKER"
	// TfReplicaSpecReplicaTypePS captures enum value "PS"
	TfReplicaSpecReplicaTypePS string = "PS"
)

// prop value enum
func (m *TfReplicaSpec) validateReplicaTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, tfReplicaSpecTypeReplicaTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TfReplicaSpec) validateReplicaType(formats strfmt.Registry) error {

	if swag.IsZero(m.ReplicaType) { // not required
		return nil
	}

	// value enum
	if err := m.validateReplicaTypeEnum("replicaType", "body", m.ReplicaType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TfReplicaSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TfReplicaSpec) UnmarshalBinary(b []byte) error {
	var res TfReplicaSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
